#!/bin/sh
# When string is given, use it as commit message
# Open $EDITOR otherwise
# Usage: gc <commit message or nothing>

gc() {
  if ((${#1[@]})) ; then
    git commit -m $1
  else
    git commit
  fi
}
