#!/bin/sh
#
# Usage: slow_port [port_number] (default 80)
# Description: Make port 80 "real life" speeds. You can also specify any other port.
slow_port {
  # Set the port variable if no port inputted. Defaulted to 80 (for Passenger).
  if [ -z "$1" ]
  then port=80
  else port=$1
  fi
}
